baseURL = "https://site.shliv.com/"
languageCode = "zh-CN"
title = "网址导航"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishdir = "docs"
copyright = "2023"
[params]
  author = "shliv.com"
  description = "网址导航"
[params.search]
  enable = true
[params.darkmode]
  enable = false